In [2]:
import pandas as pd

player_data = [
    ['Player 1', 32, 75, 5428000], ['Player 2', 33, 74, 3428000],
    ['Player 3', 34, 70, 8428000], ['Player 4', 35, 80, 4428000],
    ['Player 5', 36, 100, 4528000], ['Player 6', 38, 72, 7028000],
    ['Player 7', 22, 85, 2528000]
]
df = pd.DataFrame(player_data, columns = ['Name', 'Age', 'Weight', 'Salary'])
df

       Name  Age  Weight   Salary
0  Player 1   32      75  5428000
1  Player 2   33      74  3428000
2  Player 3   34      70  8428000
3  Player 4   35      80  4428000
4  Player 5   36     100  4528000
5  Player 6   38      72  7028000
6  Player 7   22      85  2528000

In [3]:
df_first_four_rows = df.iloc[0:4]
df_first_four_rows

       Name  Age  Weight   Salary
0  Player 1   32      75  5428000
1  Player 2   33      74  3428000
2  Player 3   34      70  8428000
3  Player 4   35      80  4428000

In [4]:
# Select only Name, Age, and Salary
df_Name_Age_Salary_cols = df.iloc[:,[0,1,3]]
df_Name_Age_Salary_cols

       Name  Age   Salary
0  Player 1   32  5428000
1  Player 2   33  3428000
2  Player 3   34  8428000
3  Player 4   35  4428000
4  Player 5   36  4528000
5  Player 6   38  7028000
6  Player 7   22  2528000

In [8]:
# Retrieve one specific salary using iloc
specific_salary = df.iloc[4,3]
print("Specific Salary:", specific_salary)

Specific Salary: 4528000

In [9]:
# Filter players whose Age is greater than 34
players_older_than_34 = df[df['Age'] > 34]
print(players_older_than_34)

       Name  Age  Weight   Salary
3  Player 4   35      80  4428000
4  Player 5   36     100  4528000
5  Player 6   38      72  7028000

In [10]:
# Create a second df with Name and Team
name_and_team = {
    'Name': ['Player 1','Player 2','Player 3','Player 4','Player 5','Player 6','Player 7'],
    'Team': ['Team A','Team B','Team A','Team C','Team B','Team C','Team A']
}

team_df = pd.DataFrame(name_and_team)
print(team_df)

       Name    Team
0  Player 1  Team A
1  Player 2  Team B
2  Player 3  Team A
3  Player 4  Team C
4  Player 5  Team B
5  Player 6  Team C
6  Player 7  Team A

In [11]:
# Merge it with the player df
merged_df = pd.merge(df, team_df)
print(merged_df)

       Name  Age  Weight   Salary    Team
0  Player 1   32      75  5428000  Team A
1  Player 2   33      74  3428000  Team B
2  Player 3   34      70  8428000  Team A
3  Player 4   35      80  4428000  Team C
4  Player 5   36     100  4528000  Team B
5  Player 6   38      72  7028000  Team C
6  Player 7   22      85  2528000  Team A

In [12]:
# Export to csv with index=False
merged_df.to_csv('merged_df.csv', index=False)