In [10]:
import pandas as pd

# Create a df with five student records.
student_records = [
    ['Lisa', 85,90,95],
    ['Amber', 92,89,100],
    ['John', 78,82,90],
    ['Jane', 88,91,85],
    ['Mary', 74,80,95]
]
df = pd.DataFrame(student_records, columns=['Student','Quiz1','Quiz2','Attendance'])
df

  Student  Quiz1  Quiz2  Attendance
0    Lisa     85     90          95
1   Amber     92     89         100
2    John     78     82          90
3    Jane     88     91          85
4    Mary     74     80          95

In [12]:
df.head(3)

  Student  Quiz1  Quiz2  Attendance
0    Lisa     85     90          95
1   Amber     92     89         100
2    John     78     82          90

In [13]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 4 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Student     5 non-null      str
 1   Quiz1       5 non-null      int64
 2   Quiz2       5 non-null      int64
 3   Attendance  5 non-null      int64
dtypes: int64(3), str(1)
memory usage: 313.0 bytes

In [14]:
df_student_quiz1_cols = df.iloc[:, 0:2]
df_student_quiz1_cols

  Student  Quiz1
0    Lisa     85
1   Amber     92
2    John     78
3    Jane     88
4    Mary     74

In [15]:
df_students_quiz1_greater_than_80 = df[df['Quiz1'] > 80].iloc[:, :]
df_students_quiz1_greater_than_80

  Student  Quiz1  Quiz2  Attendance
0    Lisa     85     90          95
1   Amber     92     89         100
3    Jane     88     91          85