In [5]:
import pandas as pd

student_records = [
    ['Lisa', 85,None,95],
    ['Amber', 92,89,100],
    ['John', 78,None,90],
    ['Jane', 88,91,85],
    ['Mary', 74,80,95]
]
df = pd.DataFrame(student_records, columns=['Student','Quiz1','Quiz2','Attendance'])
df

  Student  Quiz1  Quiz2  Attendance
0    Lisa     85    NaN          95
1   Amber     92   89.0         100
2    John     78    NaN          90
3    Jane     88   91.0          85
4    Mary     74   80.0          95

In [7]:
df_dropna = df.dropna()
df_dropna

  Student  Quiz1  Quiz2  Attendance
1   Amber     92   89.0         100
3    Jane     88   91.0          85
4    Mary     74   80.0          95

In [8]:
# Replace missing values with '0'. 
df_fillna = df.fillna(0)
df_fillna

  Student  Quiz1  Quiz2  Attendance
0    Lisa     85    0.0          95
1   Amber     92   89.0         100
2    John     78    0.0          90
3    Jane     88   91.0          85
4    Mary     74   80.0          95

In [9]:
# Compare the number of rows before and after cleaning
print("Rows before cleaning:", len(df))
print("Rows after dropna():", len(df_dropna))
print("Rows after fillna():", len(df_fillna))

Rows before cleaning: 5
Rows after dropna(): 3
Rows after fillna(): 5

# Discussion question
Dropping a row may be better when there is no appropriate value to replace the missing data and removing the row will not significantly affect the dataset. 
Filling may be better when we want to keep the row and there is an appropriate value to replace the missing data.